package Interface;

import Model.pessoas;
import Persistencia.IncluirEditarDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class jifcadastro extends javax.swing.JInternalFrame {

    int acao;
    int status;
    pessoas objpes = new pessoas();
    IncluirEditarDAO IEDAO;
    
    
    
    public jifcadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtcod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtcpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jttel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrativo = new javax.swing.JRadioButton();
        jrinativo = new javax.swing.JRadioButton();
        jbnovo = new javax.swing.JButton();
        jbeditar = new javax.swing.JButton();
        jbexcluir = new javax.swing.JButton();
        jbsalvar = new javax.swing.JButton();
        jbsair = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtend = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Cod.");

        jtnome.setEnabled(false);

        jLabel2.setText("Nome:");

        jtrg.setEnabled(false);

        jLabel3.setText("RG:");

        jLabel4.setText("CPF:");

        jtcpf.setEnabled(false);

        jLabel5.setText("Telefone:");

        jttel.setEnabled(false);

        jLabel6.setText("Endereço:");

        buttonGroup1.add(jrativo);
        jrativo.setText("Ativo");

        buttonGroup1.add(jrinativo);
        jrinativo.setText("Inativo ");

        jbnovo.setText("Novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });

        jbeditar.setText("Editar");
        jbeditar.setEnabled(false);
        jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarActionPerformed(evt);
            }
        });

        jbexcluir.setText("Excluir");
        jbexcluir.setEnabled(false);

        jbsalvar.setText("Salvar");
        jbsalvar.setEnabled(false);
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });

        jbsair.setText("Sair");
        jbsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsairActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jtend.setColumns(20);
        jtend.setRows(5);
        jtend.setEnabled(false);
        jScrollPane1.setViewportView(jtend);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jtnome)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addComponent(jScrollPane1))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jttel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jrinativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(jrativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbsair, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jbeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jtcod))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jttel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jrativo)
                        .addGap(42, 42, 42)
                        .addComponent(jrinativo))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        setBounds(300, 50, 784, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void jbsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsairActionPerformed
    dispose();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsairActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    jrativo.setSelected(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed
    
    acao=1;
    novo();
    
    }//GEN-LAST:event_jbnovoActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

    cancelar();
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarActionPerformed
    
    acao=2;
    editar();
        
    }//GEN-LAST:event_jbeditarActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed

    
    if(jrativo.isSelected()){
    status=1;
    }
    if(jrinativo.isSelected()){
    status=0;    
    }
    int cod;
    
    objpes = new pessoas();
    preencher_objetos();
    
    try {
    
    IEDAO = new IncluirEditarDAO();
    
    if(acao==1) {
        
        cod=IEDAO.Incluir(objpes);
        jtcod.setText(String.valueOf(cod));
        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
        salvar();
    }
    
    if(acao==2){
    objpes.setPes_id(Integer.parseInt(jtcod.getText()));

    if(IEDAO.Editar(objpes)) {
    JOptionPane.showMessageDialog(this, "Alterado com Sucesso !");
    salvar();
    }  
    }
    
    }catch(SQLException error) {
    JOptionPane.showMessageDialog(this, "Operação Não Realizada" + error.getMessage());
    }
       
    }//GEN-LAST:event_jbsalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeditar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jbnovo;
    private javax.swing.JButton jbsair;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JRadioButton jrativo;
    private javax.swing.JRadioButton jrinativo;
    private javax.swing.JTextField jtcod;
    private javax.swing.JTextField jtcpf;
    private javax.swing.JTextArea jtend;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtrg;
    private javax.swing.JTextField jttel;
    // End of variables declaration//GEN-END:variables

public void preencher_objetos(){
objpes.setPes_nome(jtnome.getText().trim());
objpes.setPes_rg(jtrg.getText().trim());
objpes.setPes_cpf(jtcpf.getText().trim());
objpes.setPes_end(jtend.getText().trim());
objpes.setPes_tel(jttel.getText().trim());
objpes.setPes_status(status);
}   
    
    
public void novo(){
jtnome.setEnabled(true);
jtend.setEnabled(true);
jtcpf.setEnabled(true);
jtrg.setEnabled(true);
jttel.setEnabled(true);
jtcod.setEnabled(false);
jbeditar.setEnabled(true);
jbsalvar.setEnabled(true);
jbcancelar.setEnabled(true);
jrativo.setSelected(true);
jtcod.setText("");
jtnome.setText("");
jtend.setText("");
jtcpf.setText("");
jtrg.setText("");
jttel.setText("");
                       
}

public void cancelar() {
jtcod.setText("");
jtnome.setText("");
jtend.setText("");
jtcpf.setText("");
jtrg.setText("");
jttel.setText("");
jtnome.setEnabled(false);
jtend.setEnabled(false);
jtcpf.setEnabled(false);
jtrg.setEnabled(false);
jttel.setEnabled(false);
jtcod.setEnabled(true);
jbeditar.setEnabled(false);
jbsalvar.setEnabled(false);
jbsair.setEnabled(true);
jbnovo.setEnabled(true);
jrativo.setSelected(false);
jbexcluir.setEnabled(false);
}

public void editar() {
jtnome.setEnabled(true);
jtend.setEnabled(true);
jtcpf.setEnabled(true);
jtrg.setEnabled(true);
jttel.setEnabled(true);
jtcod.setEnabled(false);
jbeditar.setEnabled(true);
jbsalvar.setEnabled(true);
jbcancelar.setEnabled(true);
jrativo.setSelected(true);
jbexcluir.setEnabled(true);
}

public void salvar(){
jtnome.setEnabled(false);
jtend.setEnabled(false);
jtcpf.setEnabled(false);
jtrg.setEnabled(false);
jttel.setEnabled(false);
jtcod.setEnabled(true);
jbeditar.setEnabled(true);
jbsalvar.setEnabled(false);
jrativo.setSelected(false);
                     
}

}


